version: "3"
services:
 web-server:
  build:
   dockerfile: Dockerfile
   context: .
  restart: always
  volumes:
   - "./orangehrm/:/var/www/html/"
  ports:
   - "8081:80"
 mysql-server:
  image: mysql:5.6
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: secret
  ports:
   - "3306:3306"
  volumes:
   - mysql-data:/var/lib/mysql

volumes:
 mysql-data:
